### ISSUE TITLE
Service IP ranges for new DCs

### ISSUE THREAD

**Issue by john-d-burke** [IBM-Bluemix-Docs/hardware-firewall-dedicated#3]
Please provide IP ranges to allow in the newer datacenters in order to allow service/provisioning in newer datacenters to complete.

**Comment by john-d-burke** [comment]
@jbmitch

**Comment by john-d-burke** [comment]
The datacenter in question is FRA05.

**Comment by jbmitch** [comment]
Hi @john-d-burke Happy to help, but which table(s) does this info need to get added to, in this document?

**Comment by jbmitch** [comment]
Fixed and pushed. Will show up here: 

https://console.bluemix.net/docs/infrastructure/hardware-firewall-dedicated/ips.html#ibm-cloud-ip-ranges
